#!/bin/bash
# Copyright 2013 Johan Rydberg.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

NAME=$1
ROOTDIR=$2
RUNCOMMAND=$3
IMAGE=$4

set -e

# Step 1.  Setup the jail.
cd $ROOTDIR
mkdir -p etc proc sys user sbin bin lib lib64 dev app

cat <<EOF > etc/resolv.conf
# Use host resolv.conf
`cat /etc/resolv.conf`

# Also use google DNS
nameserver 8.8.8.8
nameserver 8.8.4.4
EOF

cat <<EOF > etc/nsswitch.conf
hosts: files dns
EOF

cat <<EOF > etc/hostname
$NAME
EOF

cat <<EOF > etc/hosts
127.0.0.1       localhost
127.0.0.1       $NAME
EOF

cat <<EOF > etc/passwd
root:x:0:0:root:/root:/bin/bash
gilliam:x:500:500:gilliam user:/app:/bin/bash
EOF

cat <<EOF > /etc/group
root:x:0:root
gilliam:x:500:gilliam
EOF

# Setup the dev nodes.
mknod -m 666 dev/null c 1 3
mknod -m 666 dev/zero c 1 5
mknod -m 666 dev/random c 1 8
mknod -m 666 dev/urandom c 1 9
mknod -m 666 dev/tty c 5 0
mknod -m 600 dev/console c 5 1
mknod -m 666 dev/tty0 c 4 0
mknod -m 666 dev/full c 1 7
mknod -m 666 dev/ptmx c 5 2
mkdir -m 755 dev/pts
mkdir -m 1777 dev/shm
mkdir -m 1777 dev/fd

# Mount directories.
for mntpnt in proc sys usr bin sbin lib lib64 dev/pts dev/shm; do
  mount --rbind /$mntpnt $ROOTDIR/$mntpnt
done

# Extract the app.
cd $ROOTDIR/app && tar zxf $IMAGE

#CHNAME=chname $NAME
CHNAME=

# Start the runner inside the jail.
$CHNAME chroot -u 500 -g 500 $ROOTDIR $RUNCOMMAND
