#!/bin/bash
# Copyright 2013 Johan Rydberg.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ROOTDIR=$1
IMAGE=$2
TEMPLATE=/var/lib/gilliam/template

set -e

# Step 1. Copy the template
cp -ra $TEMPLATE $ROOTDIR

# Step 2. Mount key system directories.
mount -t proc proc $ROOTDIR/proc
mount -t sysfs sys $ROOTDIR/sys
mount --bind /dev/pts $ROOTDIR/dev/pts
mount --bind /dev/shm $ROOTDIR/dev/shm

# Step 3. Extract the app.
#
# We need to chroot into the jail to be able to change ownership of
# the files since the gilliam user only exists inside the jail.
mkdir -p $ROOTDIR/app
(cd $ROOTDIR/app && tar zxf $IMAGE)
chroot $ROOTDIR /bin/chown -R gilliam:gilliam /app
