#!/usr/bin/python
# Copyright 2013 Johan Rydberg.  -*- python -*-
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import json
import os
import sys

static = {'HOME': '/app'}

if __name__ == '__main__':
    cmd = json.loads(sys.stdin.readline())
    os.chdir("/app")
    environ = os.environ.copy()
    environ.update(cmd['env'])
    environ.update(static)
    os.execve("/bin/bash", ["/bin/bash", "-l", "-c", cmd["command"]], environ)
    sys._exit(1)
